######################################################################
# Automatically generated by qmake (3.0) ?? 11? 5 10:11:15 2018
######################################################################

TEMPLATE = app
TARGET = _004_HelloWorld_ui_manul
INCLUDEPATH += .

# Input
HEADERS += ui_hellodialog.h
FORMS += hellodialog.ui
SOURCES += main.cpp

#liuxingjun++
QT += widgets
